version: '3'

networks:
  internal:

services:
  server:
    build: .
    env_file:
      - .env
    container_name: go-container
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    volumes:
      - .:/usr/src/app
    command: go run cmd/main.go -b 0.0.0.0
    networks:
      internal:

  postgres:
    image: postgres
    container_name: postgres-container
    ports:
      - "5432:5432"
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      internal:

volumes:
  db-data:
