version: "3.8"

networks:
  internal:


services:

  postgres:
    container_name: postgres
    image: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "${PSQL_PORT}:${PSQL_PORT}"
    restart: unless-stopped
    networks:
      internal:

  app:
    container_name: app
    build: .
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - postgres
    restart: unless-stopped
    networks:
      internal:

volumes:
  db-data: